import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { PrimeReactProvider } from 'primereact/api';
import 'primereact/resources/themes/lara-light-amber/theme.css';
import 'primereact/resources/primereact.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import './styles.css';
import App from './App';
createRoot(document.getElementById('root')).render(<React.StrictMode><PrimeReactProvider><BrowserRouter><App/></BrowserRouter></PrimeReactProvider></React.StrictMode>);
